name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

  pull_request:

jobs:
    test-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Log in to package registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ github.token }}

            - name: ht_full_test_search tests
              run: |
                docker compose up -d 

                docker compose exec full_text_searcher python -m pytest
