services:
  full_text_searcher:
    build:
      context: .
      target: runtime
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        ENV: ${ENV:-dev}
        POETRY_VERSION: ${POETRY_VERSION:-1.5.1}
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    depends_on:
      solr-lss-dev:
        condition: service_healthy
    tty: true
    container_name: full_text_searcher
  full_text_search_api:
    build:
      context: .
      target: runtime
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        ENV: ${ENV:-dev}
        POETRY_VERSION: ${POETRY_VERSION:-1.5.1}
    env_file:
      - .env
    stdin_open: true
    depends_on:
      solr-lss-dev:
        condition: service_healthy
    tty: true
    container_name: full_text_search_api
    ports:
      - "8000:8000"
    command: [ "python", "main.py", "--env", $ENV ]
  test:
    container_name: full_text_searcher_test
    build: .
    volumes:
      - .:/app
    command: [ "pytest" ]
    depends_on:
      solr-lss-dev:
        condition: service_healthy
  solr-lss-dev:
    image: ghcr.io/hathitrust/full-text-search-embedded_zoo_data_sampling:example-8.11
    container_name: solr-lss-dev
    ports:
        - "8983:8983"
    volumes:
        - solr_data:/var/solr/data
    command: solr-foreground -c
    healthcheck:
        test: [ "CMD-SHELL", "solr healthcheck -c core-x" ]
        interval: 5s
        timeout: 10s
        start_period: 30s
        retries: 5
  data_loader: # It is probably for this application I should create the image first
    image: ghcr.io/hathitrust/lss_solr_configs-data_loader:data_sampling
    entrypoint: [ "/bin/sh", "-c" ,"indexing_data.sh http://solr-lss-dev:8983" ]
    volumes:
      - solr_data:/var/solr/data
    depends_on:
      solr-lss-dev:
        condition: service_healthy
volumes:
    solr_data:
    app:
