all:
  facet:
    - facet.mincount: 1
    - facet: "on"
    - facet.limit: 30
    - facet.field: [ "topicStr",
                     "authorStr",
                     "language008_full",
                     "countryOfPubStr",
                     "bothPublishDateRange",
                     "format",
                     "htsource",
                     "callnoletters"
      ]

  fl: [ "id",
        "title",
        "language008_full",
        "countryOfPubStr",
        "bothPublishDateRange",
        "htsource",
        "score"]
only_facets:
  facet:
    - facet.mincount: 0
    - facet: "on"
    - facet.limit: 500
    - rows: 0
    - facet.field: [ "language008_full",
                     "countryOfPubStr",
                     "bothPublishDateRange",
                     "htsource",
                     "callnoletters",
                    "rights"]
  fl: [ "id",
        "title",
        "authorStr",
        "topicStr",
        "language008_full",
        "countryOfPubStr",
        "bothPublishDateRange",
        "format",
        "htsource",
        "score" ]