MYQLS_METADATA = ['coll_id', 'ht_heldby', 'ht_heldby_brlm', 'rights']

To_CHECK = ['ht_cover_tag','ht_page_feature','ht_reading_order','ht_scanning_order','numPages',
'numChars','charsPerPage','seq','pgnum','type_s','chunk_seq', 'mainauthor', 'timestamp',
            'ctrlnum', 'rptnum', 'isbn',
            'language008_full', # it seems to be the same value as language field in Catalog
            'edition',
            'author_top',
            'author_rest',
            'authorSort',
            'author_sortkey',
            'vtitle',
            'vtitle_dv',
            'title_c',
            'title_c_dv',
            'title_sortkey',
            'title_display',
            'title',
            'titleSort',
            'titleSort_dv',
            'Vtitle',
            'Vtitle_dv',
            'title_ab',
            'title_a',
            'titleProper',
            'title_top',
            'title_topProper',
            'title_restProper',
            'title_rest',
            'fullgenre',
            'genre',
            'hlb3Str',
            'hlb3Delimited',
            'enumPublishDate',
            'bothPublishDate',
            'era',
            'fullgeographic',
            ]

CATALOG_METADATA = ['id',
                    'ocr',
                    'author',
                    'author2',
                    'date',
                    'record_no',
                    'allfields',
                    'lccn',
                    'sdrnum',
                    'oclc',
                    'issn',
                    'ht_id_display',
                    'isn_related',
                    'callnumber',
                    'sudoc',
                    'language',
                    'format',
                    'htsource',
                    'publisher',
                    'Vauthor', # eq to author
                    'volume_enumcron',
                    'series',
                    'series2',
                    'serialTitle_ab',
                    'serialTitle_a',
                    'serialTitle',
                    'serialTitle_rest',
                    'topicStr',
                    'publishDate',
                    'geographicStr',
                    'countryOfPubStr'
                    ]

OTHER_METADATA = ['vol_id', 'coll_id', 'ht_cover_tag', 'ht_page_feature', 'ht_reading_order', 'ht_scanning_order',
                  'ht_heldby', 'ht_heldby_brlm', 'numPages', 'numChars', 'charsPerPage', 'seq', 'pgnum', 'type_s',
                  'chunk_seq', 'rights', 'mainauthor', 'author', 'author2', 'date', 'timestamp', 'record_no',
                  'allfields', 'ctrlnum', 'rptnum', 'isbn', 'sudoc', 'edition', 'Vauthor', 'author_top', 'author_rest',
                  'authorSort', 'author_sortkey', 'vtitle', 'title_c', 'volume_enumcron', 'Vtitle', 'series', 'series2',
                  'fullgenre', 'genre', 'hlb3Str', 'hlb3Delimited', 'enumPublishDate', 'bothPublishDate', 'era',
                  'geographicStr', 'fullgeographic', 'ocr']
