version: "3"

services:
  document_retriever:
    container_name: document_retriever
    image: document_generator
    volumes:
      - ../tmp:/tmp:rm
      - ../sdr1/obj:/sdr1/obj
    ports:
      - "8081:8081"
    environment:
      - SOLR_URL=http://solr-sdr-catalog:9033/solr/#/catalog/
      - SDR_DIR=/sdr1/obj
      - QUEUE_HOST=rabbitmq
      - QUEUE_NAME=retriever_queue
      - QUEUE_PASS=guest
      - QUEUE_USER=guest
    depends_on:
      solr-sdr-catalog:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
      mysql-sdr:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    tty: true
    stdin_open: true
  mysql-sdr:
    image: ghcr.io/hathitrust/db-image
    volumes:
      - mysql_sdr_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=mysql-sdr
      - MYSQL_USER=mdp-lib
      - MYSQL_PASS=mdp-lib
      - MYSQL_DATABASE=ht
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect"
        ]
      timeout: 30s
  solr-lss-dev:
    image: ghcr.io/hathitrust/full-text-search-embedded_zoo:example-8.11
    container_name: solr-lss-dev
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
    command: solr-foreground -c
    healthcheck:
      test: [ "CMD-SHELL", "solr healthcheck -c core-x" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
  solr-sdr-catalog:
    container_name: solr-sdr-catalog
    image: ghcr.io/hathitrust/catalog-solr-sample
    healthcheck:
      test: [ "CMD", "/usr/bin/curl", "-s", "-f", "http://localhost:9033/solr/catalog/admin/ping" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      - "9033:9033"
    expose:
      - 9033
  test:
    container_name: indexing_test
    build: .
    volumes:
      - .:/app
      - ../tmp:/tmp
    command: [ "pytest" ]
    depends_on:
      solr-sdr-catalog:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  document_generator:
    container_name: document_generator
    image: document_generator
    volumes:
      - ../tmp:/tmp:rm
      - ../sdr1/obj:/sdr1/obj
    depends_on:
      rabbitmq:
        condition: service_healthy
    tty: true
    stdin_open: true
    environment:
      - SRC_QUEUE_HOST=rabbitmq
      - SRC_QUEUE_NAME=retriever_queue
      - SRC_QUEUE_PASS=guest
      - SRC_QUEUE_USER=guest
      - TGT_QUEUE_HOST=rabbitmq
      - TGT_QUEUE_NAME=indexer_queue
      - TGT_QUEUE_PASS=guest
      - TGT_QUEUE_USER=guest
  document_indexer:
    container_name: document_indexer
    image: document_generator
    volumes:
      - ../tmp:/tmp:rm
    ports:
      - "8082:8082"
    depends_on:
      solr-lss-dev:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    tty: true
    stdin_open: true
    environment:
      - QUEUE_HOST=rabbitmq
      - QUEUE_NAME=indexer_queue
      - QUEUE_PASS=guest
      - QUEUE_USER=guest
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
volumes:
  solr_data:
  mysql_sdr_data:

