version: "3"
services:
  ht_indexer_api:
    build: .
    command: [ "python", "main.py", "--host", "0.0.0.0", "--port", "8081", "--solr_url", "http://host.docker.internal:9033/solr/#/catalog/" ]
    image: app_ht_indexer
    ports:
      - "8081:8081"
    volumes:
      - .:/app

  solr-lss-dev:
    image: ghcr.io/hathitrust/lss-solr:unstable
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "-q", "http://localhost:8983/solr/core-x/admin/ping"]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      - "8983:8983"

  solr-sdr-catalog:
    image: ghcr.io/hathitrust/catalog-solr-sample
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-s", "-f", "http://localhost:9033/solr/catalog/admin/ping"]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      - "9033:9033"

  test:
    build: .
    volumes: 
      - .:/app
    command: ["pytest"]
    depends_on:
      solr-lss-dev:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
