services:
  document_retriever:
    container_name: document_retriever
    image: document_generator
    volumes:
      - ../tmp:/tmp:rm
      - ../sdr1/obj:/sdr1/obj
      - .:/app
    ports:
      - "8081:8081"
    environment:
      SOLR_URL: http://solr-sdr-catalog:9033/solr/#/catalog/
      SDR_DIR: /sdr1/obj
      QUEUE_HOST: rabbitmq
      QUEUE_NAME: retriever_queue
      QUEUE_PASS: guest
      QUEUE_USER: guest
    depends_on:
      solr-sdr-catalog:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    tty: true
    stdin_open: true
  mysql-sdr:
    image: ghcr.io/hathitrust/db-image
    volumes:
      - mysql_sdr_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysql-sdr
      MYSQL_USER: mdp-lib
      MYSQL_PASS: mdp-lib
      MYSQL_DATABASE: ht
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect"
        ]
      timeout: 30s
  solr-lss-dev:
    image: ghcr.io/hathitrust/full-text-search-cloud:shards-docker
    container_name: solr-lss-dev
    ports:
      - "8983:8983"
    environment:
      ZK_HOST: zoo1:2181
      SOLR_OPTS: -XX:-UseLargePages
      SOLR_USER: admin
      SOLR_PASSWORD: solrRocks
    depends_on:
      zoo1:
        condition: service_healthy
    volumes:
      - solr1_data:/var/solr/data
    # start solr in the background, wait for it to start, then create the collection
    command: [ "sh", "-c", 'solr-foreground -c & sleep 150 && export SOLR_AUTHENTICATION_OPTS=-Dbasicauth=admin:solrRocks && solr create_collection -d /opt/solr/core-x -c core-x -shards 1 -replicationFactor 1 -p 8983 && wait' ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -u admin:solrRocks 'http://localhost:8983/solr/admin/collections?action=CLUSTERSTATUS&collection=core-x' | grep -q '\"state\":\"active\"'" ]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 10
  zoo1:
    image: zookeeper:3.8.0
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - zoo1_data:/data
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok" ]
      interval: 30s
      timeout: 10s
      retries: 5
  solr-sdr-catalog:
    container_name: solr-sdr-catalog
    image: ghcr.io/hathitrust/catalog-solr-sample
    healthcheck:
      test: [ "CMD", "/usr/bin/curl", "-s", "-f", "http://localhost:9033/solr/catalog/admin/ping" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      - "9033:9033"
    expose:
      - 9033
  document_generator:
    container_name: document_generator
    image: document_generator
    volumes:
      - ../tmp:/tmp:rm
      - ../sdr1/obj:/sdr1/obj
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql-sdr:
        condition: service_healthy
    tty: true
    stdin_open: true
    environment:
      SRC_QUEUE_HOST: rabbitmq
      SRC_QUEUE_NAME: retriever_queue
      SRC_QUEUE_PASS: guest
      SRC_QUEUE_USER: guest
      TGT_QUEUE_HOST: rabbitmq
      TGT_QUEUE_NAME: indexer_queue
      TGT_QUEUE_PASS: guest
      TGT_QUEUE_USER: guest
    command: [ "python", "document_generator/document_generator_service.py" ]
  document_indexer:
    container_name: document_indexer
    image: document_generator
    volumes:
      - ../tmp:/tmp:rm
    ports:
      - "8082:8082"
    depends_on:
      solr-lss-dev:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    tty: true
    stdin_open: true
    environment:
      QUEUE_HOST: rabbitmq
      QUEUE_NAME: indexer_queue
      QUEUE_PASS: guest
      QUEUE_USER: guest
      SOLR_USER: admin
      SOLR_PASSWORD: 'solrRocks'
    command: [ "python", "document_indexer_service/document_indexer_service.py", "--solr_indexing_api", "http://solr-lss-dev:8983/solr/#/core-x/", "--batch_size", "100" ]
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
  all_tests:
    container_name: all_tests
    build: .
    volumes:
      - .:/app
      - ../tmp:/tmp
    command: [ "pytest" ]
    depends_on:
      solr-sdr-catalog:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
volumes:
  mysql_sdr_data:
  solr1_data: null
  zoo1_data: null

