version: "3"
services:
  ht_indexer_api:
    build: .
    #command: ["poetry", "run", "uvicorn", "main:app",
    #          "--host", 'localhost', "--port", "8081",
    #          "--solr_host", "host.docker.internal", "--solr_port", "8983",
    #          "--reload"]
    command: ["poetry", "run", "python", "main.py", "--host", "0.0.0.0", "--port", "8081", "--solr_host", "host.docker.internal",
"--solr_port", "8983"]
    image: app
    ports:
      - "8081:8081"
    volumes:
      - .:/app
