version: "3"
services:
  document_retriever:
    container_name: document_retriever
    build:
      context: .
    command: [ "python", "document_retriever_service/full_text_search_retriever_service.py",
               "--mysql_host", "$MYSQL_HOST",
               "--mysql_user", "$MYSQL_USER",
               "--mysql_pass", "$MYSQL_PASS",
               "--mysql_database", "ht",
               "--solr_url", "http://172.28.0.3:9033/solr/#/catalog/" ]
    #http://0.0.0.0:9033/solr/#/catalog/
    #http://solr-sdr-catalog:9033/solr/#/catalog/
    #http://host.docker.internal:9033/solr/#/catalog/
    #http://172.28.0.3:9033/solr/#/catalog/
    volumes:
      - .:/app
      - tmp:/tmp

    depends_on:
      - solr-sdr-catalog
    environment:
      - HOST="$HOST"
      - USER="$USER"
      - PUBLIC_KEY="$PUBLIC_KEY"
      #- SOLR_URL=http://solr-sdr-catalog:9033/solr/#/catalog
    networks:
      - indexer_net
  document_indexer:
    container_name: document_indexer
    build:
      context: .
    command: [ "python", "document_indexer_service/document_indexer_service.py",
               "--solr_indexing_api", "http://ht_indexer_api:8082/solrIndexing/#/core-x/",
    ]
    volumes:
      - .:/app
      - tmp:/tmp
    depends_on:
      - solr-lss-dev
      - document_retriever
      - ht_indexer_api
    networks:
      - indexer_net
  #ht_catalog_api:
  #  build: .
  #  command: [ "python", "main.py", "--host", "0.0.0.0", "--port", "8081", "--solr_url", "http://host.docker.internal:9033/solr/#/catalog/" ]
  #  image: app_ht_catalog
  #  depends_on:
  #    - solr-sdr-catalog
  #  ports:
  #    - "8081:8081"
  #  volumes:
  #    - .:/app
  ht_indexer_api:
    build: .
    container_name: ht_indexer_api
    command: [ "python", "main.py", "--host", "0.0.0.0", "--port", "8082", "--solr_url", "http://host.docker.internal:8983/solr/#/core-x/" ]
    image: app_ht_indexer
    depends_on:
      - solr-lss-dev
    ports:
      - "8082:8082"
    volumes:
      - .:/app
  solr-lss-dev:
    image: ghcr.io/hathitrust/lss-solr:unstable
    healthcheck:
      test: [ "CMD", "/usr/bin/wget", "-q", "http://localhost:8983/solr/core-x/admin/ping" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      - "8983:8983"
    environment:
      - SOLR_HEAP=2g
  solr-sdr-catalog:
    container_name: solr-sdr-catalog
    image: ghcr.io/hathitrust/catalog-solr-sample
    healthcheck:
      test: [ "CMD", "/usr/bin/curl", "-s", "-f", "http://localhost:9033/solr/catalog/admin/ping" ]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    ports:
      - "9033:9033"
    #environment:
    #- SOLR_HOST="solr-sdr-catalog"
    networks:
      - indexer_net
    #volumes:
    #  - solr_sdr_catalog:/var/solr
  test:
    container_name: indexing_test
    build: .
    volumes:
      - .:/app
      - tmp:/tmp
    command: [ "pytest" ]
    depends_on:
      solr-lss-dev:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy

networks:
  indexer_net:
volumes:
  tmp: